### ISSUE TITLE
Error when clicking "Detalles" button 

### ISSUE THREAD

**Issue by chrisgel15** [nbajko/WorldCupProde#4]
![image](https://user-images.githubusercontent.com/11690066/41421705-c06ec8ea-6fcd-11e8-8abd-fc209bea96db.png)

![image](https://user-images.githubusercontent.com/11690066/41421732-ccc417b2-6fcd-11e8-9444-5de4e3970f88.png)

**Comment by nbajko** [comment]
Gracias, ya hemos resulto el error.
